### Listar todos los productos
GET http://localhost:8080/api/productos
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJhcGkgaW52ZW50b3J5Iiwic3ViIjoiam9uYXRoYWFuIiwiaWQiOjEsImV4cCI6MTc2OTU0MjcwNX0.TzRivMT1eCS2AkBvtrAVkvsftc17IaOSA7PIktrdfO0

###

### Crear un nuevo producto (El postre)
POST http://localhost:8080/api/productos
Content-Type: application/json

{ "nombre": "Producto Fallido",
  "precio": -10.50,
  "stock": 5
}
### Separador
DELETE http://localhost:8080/api/categorias/1



### Borrar el producto con ID 6 (el que no tiene precio)
DELETE http://localhost:8080/api/productos/1

### Actualizar el producto 1 (Coca Cola)
PUT http://localhost:8080/api/productos/1
Content-Type: application/json
### Probando el buscador
GET http://localhost:8080/api/productos/2

### Separador
//agregar categorias a la base de datos
POST http://localhost:8080/api/categorias
Content-Type: application/json

{
  "nombre": "Postres"
}

### Separador
//unir un proucto a una categoria
POST http://localhost:8080/api/productos
Content-Type: application/json

{
  "nombre": "Tiramisu",
  "precio": 69.00,
  "stock": 30,
  "categoria": {
    "id": 4
  }
}

### Separador

GET http://localhost:8080/api/categorias

### Separador

DELETE http://localhost:8080/api/productos/7

### Separador
POST http://localhost:8080/api/productos/2/movimientos
Content-Type: application/json

{
  "tipo": "ENTRADA",
  "cantidad": 50
}


### Ver historial del producto 2
GET http://localhost:8080/api/productos/2/movimientos

###

POST http://localhost:8080/api/productos/2/movimientos
Content-Type: application/json

{
  "tipo": "ENTRADA",
  "cantidad": 0
}



### Separador
POST http://localhost:8080/login
Content-Type: application/json

{
  "email": "jonathaan",
  "password": "jonadev"
}

### Registrar un nuevo usuario
POST http://localhost:8080/usuarios
Content-Type: application/json

{
  "email": "alicia@email.com",
  "password": "password123"
}